import { adminApi } from '../api/apiClient';

/**
 * Seeds the database with premium demo properties.
 * Uses local artifact paths for images generated by Antigravity.
 */
export const seedPremiumProperties = async () => {
  const properties = [
    {
      hotel: {
        name: "Azure Haven Resort",
        city: "Maldives",
        address: "North Atoll, Paradise Island",
        description: "A breathtaking luxury overwater villa experience. Turquoise waters, private decks, and world-class service await you in this island paradise.",
        imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80" // Fallback high-end URL
      },
      rooms: [
        { type: "Ocean Villa", basePrice: 1200, totalCount: 5, capacity: 2 },
        { type: "Presidential Water Suite", basePrice: 2500, totalCount: 2, capacity: 4 }
      ]
    },
    {
      hotel: {
        name: "Skyline Elite Suites",
        city: "New York",
        address: "5th Avenue, Manhattan",
        description: "Ultra-modern living in the heart of the city. Floor-to-ceiling windows with breathtaking skyscraper views and minimalist luxury design.",
        imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80"
      },
      rooms: [
        { type: "Manhattan Suite", basePrice: 650, totalCount: 10, capacity: 2 },
        { type: "Penthouse Loft", basePrice: 1500, totalCount: 2, capacity: 3 }
      ]
    },
    {
      hotel: {
        name: "Everest Peak Lodge",
        city: "Zermatt",
        address: "Matterhorn Trail 42",
        description: "A cozy mountain retreat in the Swiss Alps. Featuring warm fireplaces, snowy panoramas, and the perfect base for your skiing adventures.",
        imageUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=80"
      },
      rooms: [
        { type: "Alpine Cabin", basePrice: 450, totalCount: 8, capacity: 2 },
        { type: "Family Stone Lodge", basePrice: 850, totalCount: 4, capacity: 6 }
      ]
    }
  ];

  const results = [];
  for (const item of properties) {
    // 1. Create Hotel
    const hotel = await adminApi.createHotel(item.hotel);
    
    // 2. Add Rooms
    for (const roomData of item.rooms) {
      await adminApi.addRoom(hotel.id, roomData);
    }
    
    // 3. Activate
    await adminApi.activateHotel(hotel.id);
    
    results.push(hotel);
  }
  
  return results;
};
